#!/bin/sh
# lets me do some stuff with a browser pretty easily from cli a bit annoying with cases of multiple words in a query but I can't be bothered fucking around with bash/shell index slicing or whatever
if [ $1 == "loc" ]; then
    firefox --new-tab "https://www.openstreetmap.org/search?query=""$2"
elif [ $1 == "search" ]; then
    firefox --search "$2"
elif [ $1 == "yt" ]; then
    firefox --search "yt! ""$2"
fi
